/* contrib/lpathtree/lpathtree--unpackaged--1.0.sql */

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION lpathtree" to load this file. \quit

ALTER EXTENSION lpathtree ADD type lpathtree;
ALTER EXTENSION lpathtree ADD function lpathtree_in(cstring);
ALTER EXTENSION lpathtree ADD function lpathtree_out(lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_cmp(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_lt(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_le(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_eq(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_ge(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_gt(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_ne(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator >(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator >=(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator <(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator <=(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator <>(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator =(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function sublpathtree(lpathtree,integer,integer);
ALTER EXTENSION lpathtree ADD function subpath(lpathtree,integer,integer);
ALTER EXTENSION lpathtree ADD function subpath(lpathtree,integer);
ALTER EXTENSION lpathtree ADD function index(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function index(lpathtree,lpathtree,integer);
ALTER EXTENSION lpathtree ADD function nlevel(lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree2text(lpathtree);
ALTER EXTENSION lpathtree ADD function text2lpathtree(text);
ALTER EXTENSION lpathtree ADD function lca(lpathtree[]);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lca(lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_isparent(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_risparent(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_addlpathtree(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtree_addtext(lpathtree,text);
ALTER EXTENSION lpathtree ADD function lpathtree_textadd(text,lpathtree);
ALTER EXTENSION lpathtree ADD function lpathtreeparentsel(internal,oid,internal,integer);
ALTER EXTENSION lpathtree ADD operator <@(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator @>(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator ^<@(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator ^@>(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator ||(lpathtree,lpathtree);
ALTER EXTENSION lpathtree ADD operator ||(lpathtree,text);
ALTER EXTENSION lpathtree ADD operator ||(text,lpathtree);
ALTER EXTENSION lpathtree ADD operator family lpathtree_ops using btree;
ALTER EXTENSION lpathtree ADD operator class lpathtree_ops using btree;
ALTER EXTENSION lpathtree ADD type lpathquery;
ALTER EXTENSION lpathtree ADD function lpathquery_in(cstring);
ALTER EXTENSION lpathtree ADD function lpathquery_out(lpathquery);
ALTER EXTENSION lpathtree ADD function ltq_regex(lpathtree,lpathquery);
ALTER EXTENSION lpathtree ADD function ltq_rregex(lpathquery,lpathtree);
ALTER EXTENSION lpathtree ADD operator ~(lpathquery,lpathtree);
ALTER EXTENSION lpathtree ADD operator ~(lpathtree,lpathquery);
ALTER EXTENSION lpathtree ADD operator ^~(lpathquery,lpathtree);
ALTER EXTENSION lpathtree ADD operator ^~(lpathtree,lpathquery);
ALTER EXTENSION lpathtree ADD function lt_q_regex(lpathtree,lpathquery[]);
ALTER EXTENSION lpathtree ADD function lt_q_rregex(lpathquery[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ?(lpathquery[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ?(lpathtree,lpathquery[]);
ALTER EXTENSION lpathtree ADD operator ^?(lpathquery[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ^?(lpathtree,lpathquery[]);
ALTER EXTENSION lpathtree ADD type lpathtree_gist;
ALTER EXTENSION lpathtree ADD function lpathtree_gist_in(cstring);
ALTER EXTENSION lpathtree ADD function lpathtree_gist_out(lpathtree_gist);
ALTER EXTENSION lpathtree ADD function lpathtree_consistent(internal,internal,smallint,oid,internal);
ALTER EXTENSION lpathtree ADD function lpathtree_compress(internal);
ALTER EXTENSION lpathtree ADD function lpathtree_decompress(internal);
ALTER EXTENSION lpathtree ADD function lpathtree_penalty(internal,internal,internal);
ALTER EXTENSION lpathtree ADD function lpathtree_picksplit(internal,internal);
ALTER EXTENSION lpathtree ADD function lpathtree_union(internal,internal);
ALTER EXTENSION lpathtree ADD function lpathtree_same(internal,internal,internal);
ALTER EXTENSION lpathtree ADD operator family gist_lpathtree_ops using gist;
ALTER EXTENSION lpathtree ADD operator class gist_lpathtree_ops using gist;
ALTER EXTENSION lpathtree ADD function _lpathtree_isparent(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD function _lpathtree_r_isparent(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD function _lpathtree_risparent(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD function _lpathtree_r_risparent(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD function _ltq_regex(lpathtree[],lpathquery);
ALTER EXTENSION lpathtree ADD function _ltq_rregex(lpathquery,lpathtree[]);
ALTER EXTENSION lpathtree ADD function _lt_q_regex(lpathtree[],lpathquery[]);
ALTER EXTENSION lpathtree ADD function _lt_q_rregex(lpathquery[],lpathtree[]);
ALTER EXTENSION lpathtree ADD operator <@(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator @>(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator @>(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator <@(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ~(lpathquery,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ~(lpathtree[],lpathquery);
ALTER EXTENSION lpathtree ADD operator ?(lpathquery[],lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ?(lpathtree[],lpathquery[]);
ALTER EXTENSION lpathtree ADD operator ^<@(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ^@>(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ^@>(lpathtree,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ^<@(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ^~(lpathquery,lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ^~(lpathtree[],lpathquery);
ALTER EXTENSION lpathtree ADD operator ^?(lpathquery[],lpathtree[]);
ALTER EXTENSION lpathtree ADD operator ^?(lpathtree[],lpathquery[]);
ALTER EXTENSION lpathtree ADD function _lpathtree_extract_isparent(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ?@>(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD function _lpathtree_extract_risparent(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD operator ?<@(lpathtree[],lpathtree);
ALTER EXTENSION lpathtree ADD function _ltq_extract_regex(lpathtree[],lpathquery);
ALTER EXTENSION lpathtree ADD operator ?~(lpathtree[],lpathquery);
ALTER EXTENSION lpathtree ADD function _lpathtree_consistent(internal,internal,smallint,oid,internal);
ALTER EXTENSION lpathtree ADD function _lpathtree_compress(internal);
ALTER EXTENSION lpathtree ADD function _lpathtree_penalty(internal,internal,internal);
ALTER EXTENSION lpathtree ADD function _lpathtree_picksplit(internal,internal);
ALTER EXTENSION lpathtree ADD function _lpathtree_union(internal,internal);
ALTER EXTENSION lpathtree ADD function _lpathtree_same(internal,internal,internal);
ALTER EXTENSION lpathtree ADD operator family gist__lpathtree_ops using gist;
ALTER EXTENSION lpathtree ADD operator class gist__lpathtree_ops using gist;
